In [1]:
import numpy as np

In [2]:
a = np.arange(10)

In [3]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
a.reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [5]:
b = np.array([1, 54 ,1 ,564,312,1,2, 56,4,56,137,6543 ,546,5,32,145,35,435])
len(b)

18

In [6]:
np.argsort(b)

array([ 0,  2,  5,  6,  8, 13, 14, 16,  1,  7,  9, 10, 15,  4, 17, 12,  3,
       11], dtype=int64)

In [7]:
np.argmin(b)

0

In [8]:
np.argmax(b)

11

In [9]:
b = b.reshape(9, 2).copy()

In [10]:
b

array([[   1,   54],
       [   1,  564],
       [ 312,    1],
       [   2,   56],
       [   4,   56],
       [ 137, 6543],
       [ 546,    5],
       [  32,  145],
       [  35,  435]])

In [11]:
np.argsort(b, axis=1)  # Sorting along rows

array([[0, 1],
       [0, 1],
       [1, 0],
       [0, 1],
       [0, 1],
       [0, 1],
       [1, 0],
       [0, 1],
       [0, 1]], dtype=int64)

In [12]:
np.argsort(b, axis=0)  # Sorting along Columns

array([[0, 2],
       [1, 6],
       [3, 0],
       [4, 3],
       [7, 4],
       [8, 7],
       [5, 8],
       [2, 1],
       [6, 5]], dtype=int64)