In [1]:
import numpy as np

In [2]:
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])

In [3]:
arr2 = np.array([[7, 8, 9], 
                 [10, 11, 12]])

# Dot Product

In [4]:
np.dot(arr1, arr2.transpose())

array([[ 50,  68],
       [122, 167]])

# Cross Product

In [5]:
np.cross(arr1, arr2)

array([[-6, 12, -6],
       [-6, 12, -6]])

## Summing with respect to Axis - 0

In [6]:
np.sum(arr1, axis=0)  # Summing column wise i.e., axis = 0

array([5, 7, 9])

## Summing with respect to Axis - 1

In [7]:
np.sum(arr1, axis=1)  # Summing Row wise i.e., axis = 1

array([ 6, 15])

## Sorting 

In [8]:
arr1 = np.array([[1, 82, 33],
                 [4, 45, 6]])

In [9]:
np.sort(arr1, axis=0) # Sorting Column wise i.e., axis = 0

array([[ 1, 45,  6],
       [ 4, 82, 33]])

In [10]:
np.sort(arr1, axis=1) # Sorting Row wise i.e., axis = 1

array([[ 1, 33, 82],
       [ 4,  6, 45]])

In [11]:
%%time
np.sort(arr1, kind="mergesort")

Wall time: 0 ns


array([[ 1, 33, 82],
       [ 4,  6, 45]])

In [12]:
%%time
np.sort(arr1, kind="quicksort")

Wall time: 0 ns


array([[ 1, 33, 82],
       [ 4,  6, 45]])

In [13]:
%%time
np.sort(arr1, kind="stable")

Wall time: 0 ns


array([[ 1, 33, 82],
       [ 4,  6, 45]])

In [14]:
%%time
np.sort(arr1, kind="heapsort")

Wall time: 0 ns


array([[ 1, 33, 82],
       [ 4,  6, 45]])

In [15]:
np.sort(arr1, axis=None)  # When axis=None then it sort all the elements in a single list only

array([ 1,  4,  6, 33, 45, 82])