In [59]:
import numpy as np

In [60]:
array1 = np.array([1, 2, 3, 4, 5, 6, 0.5])

In [61]:
array1.dtype

dtype('float64')

In [62]:
array1

array([1. , 2. , 3. , 4. , 5. , 6. , 0.5])

## Arithematic Operations


In [63]:
array1

array([1. , 2. , 3. , 4. , 5. , 6. , 0.5])

In [64]:
array1*array1

array([ 1.  ,  4.  ,  9.  , 16.  , 25.  , 36.  ,  0.25])

In [65]:
array1/array1

array([1., 1., 1., 1., 1., 1., 1.])

In [66]:
array1+array1

array([ 2.,  4.,  6.,  8., 10., 12.,  1.])

In [67]:
array1-array1

array([0., 0., 0., 0., 0., 0., 0.])

In [68]:
array1**array1

array([1.00000000e+00, 4.00000000e+00, 2.70000000e+01, 2.56000000e+02,
       3.12500000e+03, 4.66560000e+04, 7.07106781e-01])

# Slicing

In [69]:
array1

array([1. , 2. , 3. , 4. , 5. , 6. , 0.5])

In [70]:
array1[3::]

array([4. , 5. , 6. , 0.5])

In [71]:
array1[3:5]

array([4., 5.])

In [72]:
array2 = np.array([[1, 2, 5, 24, 78, 65], [12, 5, 6, 12, 45, 23]])

In [73]:
array2.shape

(2, 6)

In [74]:
array2.dtype

dtype('int32')

In [75]:
array2

array([[ 1,  2,  5, 24, 78, 65],
       [12,  5,  6, 12, 45, 23]])

In [76]:
arr = array2[1, 2:5].copy()

In [77]:
arr

array([ 6, 12, 45])

In [78]:
arr[0] = 9

In [79]:
array2

array([[ 1,  2,  5, 24, 78, 65],
       [12,  5,  6, 12, 45, 23]])

In [82]:
array2.sort()

In [83]:
array2

array([[ 1,  2,  5, 24, 65, 78],
       [ 5,  6, 12, 12, 23, 45]])